Handle invalid migration names at migrate:stop
drush-ops/drush pull request #4777
Opened 2021-06-18 22:30 UTC by marvil07

**Describe the bug**
`migrate:stop` is not handling the case when an invalid migrate name is passed.

**To Reproduce**
Try `vendor/bin/drush migrate:stop unexisting_migration`

**Expected behavior**
An error message is presented.

**Actual behavior**
An unhandled error is reached, triggering a php fatal error.

**Workaround**
No.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x e436955b5556113dda0af8a3c4225f0b209ed329
| Drupal version? | 9.x
| PHP version     | 7.3
| OS?             | Linux

**Additional information**
Add any other context about the problem here.

Here the full output I get without the extra change on this pull request.

    $ vendor/bin/drush migrate:stop unexisting_migration
     [error]  Error: Call to a member function getStatus() on bool in Drush\Drupal\Commands\core\MigrateRunnerCommands->stop() (line 438 of vendor/drush/drush/src/Drupal/Commands/core/MigrateRunnerCommands.php) #0 [internal function]: Drush\Drupal\Commands\core\MigrateRunnerCommands->stop('unexisting_migr...', Array)
    #1 vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
    #2 vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
    #3 vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
    #4 vendor/consolidation/annotated-command/src/AnnotatedCommand.php(311): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData)) 
    #5 vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #6 vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #7 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
    #8 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #9 vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #10 vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
    #11 vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
    #12 vendor/drush/drush/drush(4): require('...')
    #13 {main}. 
    Error: Call to a member function getStatus() on bool in vendor/drush/drush/src/Drupal/Commands/core/MigrateRunnerCommands.php on line 438 #0 [internal function]: Drush\Drupal\Commands\core\MigrateRunnerCommands->stop('unexisting_migr...', Array)
    #1 vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
    #2 vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
    #3 vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
    #4 vendor/consolidation/annotated-command/src/AnnotatedCommand.php(311): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
    #5 vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #6 vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #7 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #8 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #9 vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #10 vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
    #11 vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
    #12 vendor/drush/drush/drush(4): require('...')
    #13 {main}
    Error: Call to a member function getStatus() on bool in Drush\Drupal\Commands\core\MigrateRunnerCommands->stop() (line 438 of vendor/drush/drush/src/Drupal/Commands/core/MigrateRunnerCommands.php).
     [warning] Drush command terminated abnormally.

Instead, once the changes are in place, this is the new output.

    $ vendor/bin/drush migrate:stop unexisting_migration
     [error]  Migration unexisting_migration does not exist

2021-06-20 12:18 UTC, weitzman commented
We should emulate validateConfigName() and validate migration names that are passed as arguments.

2021-07-02 21:47 UTC, marvil07 commented
@weitzman, thanks for the feedback!

I have changed the approach to use an annotated command hook for the validation of the migration name.

2021-07-03 02:33 UTC, marvil07 commented
I also noticed the same problem for both `migrate:messages` and `migrate:fields-source` commands.
And now that the last commit added a validate hook, it is natural to just use it for those other two cases.
I added a couple of changes about it, and also changed the name and description of this pull request.

@weitzman, again, nice suggestion!

2021-07-03 02:54 UTC, marvil07 commented
And it also makes sense for `migrate:reset-status`.

2021-08-17 02:45 UTC, weitzman commented
LGTM. Any concerns, @claudiu-cristea ?

2021-08-17 06:34 UTC, claudiu-cristea requested changes
Nice improvement and cleanup. I still have some minor remarks

2021-08-17 06:34 UTC, claudiu-cristea commented on src/Drupal/Commands/core/MigrateRunnerCommands.php
> +     * Validate that a migration name is valid.
s/Validate/Validates

2021-08-17 06:34 UTC, claudiu-cristea commented on src/Drupal/Commands/core/MigrateRunnerCommands.php
> +        $arg_name = $commandData->annotationData()->get('validate-migration-name', null) ?: 'migrationId';
Let's keep the local vars naming consistent as _lowerCamelCase_. Applies to `$migration_name`, `$arg_name`. Also, why not keeping `$migrationId` when we refer to migration ID, to be consistent with the other methods?

2021-08-17 06:34 UTC, claudiu-cristea commented on src/Drupal/Commands/core/MigrateRunnerCommands.php
> +        $migration = $this->getMigrationPluginManager()->createInstance($migration_name);
Creating a new instance is more expensive than checking for existing definition: `$this->getMigrationPluginManager()->hasDefinition(...)`?

2021-08-17 06:40 UTC, claudiu-cristea commented on src/Drupal/Commands/core/MigrateRunnerCommands.php
> +        $arg_name = $commandData->annotationData()->get('validate-migration-name', null) ?: 'migrationId';
The `null` default value can be removed. If missing a default value, an empty string is returned and the whole line work in the same way

2021-08-17 06:45 UTC, claudiu-cristea commented on src/Drupal/Commands/core/MigrateRunnerCommands.php
> +            return new CommandError($msg);
I guess it can go in a single line. But it's a matter of taste...

2021-08-30 17:59 UTC, merged