4588 pm enable to install
drush-ops/drush pull request #5061
Opened 2022-02-02 08:06 UTC by rajeshreeputra

2022-02-02 12:30 UTC, weitzman requested changes

2022-02-02 12:30 UTC, weitzman commented on src/Drupal/Commands/pm/PmCommands.php
> +     * @aliases install, pm-install, en, pm-enable, pm:enable
lets add `in` as an alias

2022-02-02 12:30 UTC, weitzman commented on tests/unit/ArgsRemapperTest.php
> +                ['pm:install', 'install'],
Lets test all aliases of pm:install

2022-02-03 07:48 UTC, rajeshreeputra commented on src/Drupal/Commands/pm/PmCommands.php
> +     * @aliases install, pm-install, en, pm-enable, pm:enable
added in alias for pm:install

2022-02-03 14:04 UTC, weitzman commented on src/Preflight/Preflight.php
> +            'install' => 'pm:install',
remapCommandAliases is a different thing than adding aliases in the commandfile.

2022-02-04 03:43 UTC, rajeshreeputra reviewed
updated the requested changes, please review.

2022-02-04 03:43 UTC, rajeshreeputra commented on src/Preflight/Preflight.php
> +            'install' => 'pm:install',
added mapping for all aliases for pm:install

2022-04-15 19:00 UTC, merged