Twig debug
drush-ops/drush pull request #5668
Opened 2023-06-20 18:20 UTC by Chi-teck

This adds Drush command to enable/disable Twig debug mode.

This was previously requested as part of #5109. However, the proposed `site:mode` command is too wide, indeed. And it may need a lot of options to fit everyone's needs.

Unlike most of `site:mode` settings Twig debug mode cannot be set through settings.php or `drush cset`. It requires changing Twig parameters in `development.services.yml` file and rebuilding container. However, since Drupal 10.1.0 there is [a way](https://www.drupal.org/node/3359728) to enable it through Drupal states. So that the `drush twig:debug` command can be really simple.

Relevant issue on drupal.org
https://www.drupal.org/project/drupal/issues/3363676

2023-07-06 11:58 UTC, weitzman requested changes

2023-07-06 11:58 UTC, weitzman commented on src/Commands/core/TwigCommands.php
> +     * Enables Twig debug and disables caching Twig tempaltes.
```suggestion
     * Enables Twig debug and disables caching Twig templates.
```

2023-07-06 11:58 UTC, weitzman commented on src/Commands/core/TwigCommands.php
> +    #[CLI\Argument(name: 'mode', description: 'Debug mode (on/off).')]
```suggestion
    #[CLI\Argument(name: 'mode', description: 'Debug mode. Recognized values: <info>on</info>, <info>off</info>.', suggestedValues: ['on', 'off'])]
```

2023-07-06 12:34 UTC, Chi-teck commented
Fixed version number comparison.

2023-07-06 14:28 UTC, merged

2025-04-05 10:09 UTC, gitressa commented
Thanks! I tried enabling this feature, but can't see any changes ... where should I see the effect of this command?

```
$ drush twig:debug on
 [OK] Enabled twig debug.
```

2025-04-05 12:10 UTC, Chi-teck commented
That's just a CLI interface for admin/config/development/settings.

Apparently, it's no longer working because of https://www.drupal.org/node/3437162

2025-04-05 12:30 UTC, weitzman commented
Ugh. I wish Drupal would make an API for stuff like this. Then callers like Drush would be isolated from implementation shanges. Raw key-value is not an API.